# Generated by Django 3.0.3 on 2020-04-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200406_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'due_back', 'imprint'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
